import { FilesAndFolder, NavBarItems } from "@/Interfaces/interfaces";
import { createSlice, PayloadAction } from "@reduxjs/toolkit";
let theID = 0;
const initialState: NavBarItems = {
  Myfiles: [
    {
      id: ++theID,
      selected: false,
      title: "VScode Clone",
      isFolder: true,
      content: "",
      children: [
        {
          id: ++theID,
          selected: false,
          title: "node_modules",
          isFolder: true,
          content: "",
          children: [
            {
              id: ++theID,
              selected: false,
              title: "Vite",
              isFolder: true,
              content: "",
              children: [
                {
                  id: ++theID,
                  selected: false,
                  title: "index.js",
                  isFolder: false,
                  content: "",
                  children: null,
                },
              ],
            },
            {
              id: ++theID,
              selected: false,
              title: "index.ts",
              isFolder: false,
              children: null,
              content: "",
            },
          ],
        },
        {
          id: ++theID,
          selected: false,
          title: "src",
          isFolder: true,
          content: "",
          children: [
            {
              id: ++theID,
              selected: false,
              title: "assets",
              isFolder: true,
              children: null,
              content: "",
            },
            {
              id: ++theID,
              selected: false,
              title: "components",
              isFolder: true,
              content: "",
              children: [
                {
                  id: ++theID,
                  selected: false,
                  title: "Button.tsx",
                  isFolder: false,
                  content: "",
                  children: null,
                },
                {
                  id: ++theID,
                  selected: false,
                  title: "Input.tsx",
                  isFolder: false,
                  children: null,
                  content: "",
                },
              ],
            },
            {
              id: ++theID,
              selected: false,
              title: "interfaces",
              isFolder: true,
              content: "",
              children: [
                {
                  id: ++theID,
                  selected: false,
                  title: "interfase.ts",
                  isFolder: false,
                  content: "",
                  children: null,
                },
              ],
            },
            {
              id: ++theID,
              selected: false,
              title: "layouts",
              isFolder: true,
              children: null,
              content: "",
            },
            {
              id: ++theID,
              selected: false,
              title: "Redux",
              isFolder: true,
              children: null,
              content: "",
            },
            {
              id: ++theID,
              selected: false,
              title: "Routers",
              isFolder: true,
              children: null,
              content: "",
            },
            {
              id: ++theID,
              selected: false,
              title: "App.css",
              isFolder: false,
              children: null,
              content: "",
            },
            {
              id: ++theID,
              selected: false,
              title: "App.tsx",
              isFolder: false,
              children: null,
              content: "",
            },
            {
              id: ++theID,
              selected: false,
              title: "index.css",
              isFolder: false,
              content: "",
              children: null,
            },
            {
              id: ++theID,
              selected: false,
              title: "index.tsx",
              isFolder: false,
              content: "",
              children: null,
            },
          ],
        },
        {
          id: ++theID,
          selected: false,
          title: "index.html",
          isFolder: false,
          children: null,
          content: "",
        },
        {
          id: ++theID,
          selected: false,
          title: "index.ts",
          isFolder: false,
          children: null,
          content: "",
        },
        {
          id: ++theID,
          selected: false,
          title: "index.css",
          isFolder: false,
          children: null,
          content: "",
        },
        {
          id: ++theID,
          selected: false,
          title: "index.py",
          isFolder: false,
          children: null,
          content: "",
        },
        {
          id: ++theID,
          selected: false,
          title: "index.cpp",
          isFolder: false,
          children: null,
          content: "",
        },
        {
          id: ++theID,
          selected: false,
          title: "index.txt",
          isFolder: false,
          children: null,
          content: "",
        },
      ],
    },
  ],
  openFiles: [],
};
export const files = createSlice({
  name: "files",
  initialState,
  reducers: {
    setOpenFiles: (state, action: PayloadAction<FilesAndFolder>) => {
      state.openFiles = [...state.openFiles, action.payload];
    },
  },
});
export const { setOpenFiles } = files.actions;
export default files.reducer;
